//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDetail
    {
        public long AppDetailID { get; set; }
        public string DescriptionInHTML1 { get; set; }
        public string DescriptionInHTML2 { get; set; }
        public string DescriptionInHTML3 { get; set; }
        public string DescriptionInHTML4 { get; set; }
    
        public virtual App App { get; set; }
    }
}
