//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogAppRelation
    {
        public long BlogAppRelationID { get; set; }
        public long BlogID { get; set; }
        public long AppID { get; set; }
    
        public virtual App App { get; set; }
        public virtual Blog Blog { get; set; }
    }
}
