//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadFileDraft
    {
        public System.Guid UploadFileDraftID { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<long> UseID { get; set; }
        public Nullable<int> GalleryCategoryID { get; set; }
        public bool IsUsed { get; set; }
        public short FileTypeID { get; set; }
        public long FileSizeMB { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual GalleryCategory GalleryCategory { get; set; }
    }
}
