//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertise
    {
        public long AdvertiseID { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Description { get; set; }
        public System.DateTime PublishAt { get; set; }
        public Nullable<System.DateTime> EndAt { get; set; }
        public bool IsLifeTime { get; set; }
        public long PaymentID { get; set; }
        public string YoutubeVideoID { get; set; }
        public byte AdvertiseCategoryID { get; set; }
    
        public virtual AdvertiseCategory AdvertiseCategory { get; set; }
        public virtual Payment Payment { get; set; }
    }
}
