//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blog()
        {
            this.Blog1 = new HashSet<Blog>();
            this.BlogAppRelations = new HashSet<BlogAppRelation>();
            this.BlogFiles = new HashSet<BlogFile>();
            this.SearchedBlogArticleFounds = new HashSet<SearchedBlogArticleFound>();
            this.TagBlogRelations = new HashSet<TagBlogRelation>();
        }
    
        public long BlogID { get; set; }
        public string Title { get; set; }
        public string Article { get; set; }
        public bool ContainsFiles { get; set; }
        public int BlogCategoryID { get; set; }
        public long UserID { get; set; }
        public bool IsDraft { get; set; }
        public System.DateTime PublishedAt { get; set; }
        public System.DateTime DraftAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public short ReportedCount { get; set; }
        public long ViewsCount { get; set; }
        public long LikedCount { get; set; }
        public long DislikedCount { get; set; }
        public bool IsGalleryPresent { get; set; }
        public Nullable<System.DateTime> TakeOffAfter { get; set; }
        public Nullable<short> CssStyleID { get; set; }
        public string Tags { get; set; }
        public string Slug { get; set; }
        public byte[] SHA256 { get; set; }
        public Nullable<long> ParentBlogID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Blog> Blog1 { get; set; }
        public virtual Blog Blog2 { get; set; }
        public virtual BlogCategory BlogCategory { get; set; }
        public virtual BlogDetail BlogDetail { get; set; }
        public virtual CssStyle CssStyle { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogAppRelation> BlogAppRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlogFile> BlogFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchedBlogArticleFound> SearchedBlogArticleFounds { get; set; }
        public virtual ICollection<TagBlogRelation> TagBlogRelations { get; set; }
    }
}
