//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatConversation
    {
        public long ChatConversationID { get; set; }
        public long ChatID { get; set; }
        public bool IsUser1Sending { get; set; }
        public System.DateTime Time { get; set; }
        public string Message1 { get; set; }
        public string Message2 { get; set; }
        public bool IsDelivered { get; set; }
    
        public virtual Chat Chat { get; set; }
    }
}
