//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chat()
        {
            this.ChatConversations = new HashSet<ChatConversation>();
        }
    
        public long ChatID { get; set; }
        public long UserID1 { get; set; }
        public long UserID2 { get; set; }
        public System.DateTime StartedTime { get; set; }
        public bool IsSupport { get; set; }
        public bool IsResolved { get; set; }
        public byte ChatTypeID { get; set; }
        public byte RelatedIDTypeID { get; set; }
    
        public virtual ChatType ChatType { get; set; }
        public virtual RelatedIDType RelatedIDType { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatConversation> ChatConversations { get; set; }
    }
}
