//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenericSettingItem
    {
        public long GenericSettingItemID { get; set; }
        public long GenericSettingID { get; set; }
        public string ID { get; set; }
        public string Value { get; set; }
    
        public virtual GenericSetting GenericSetting { get; set; }
    }
}
