//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long NotificationID { get; set; }
        public long UserID { get; set; }
        public byte NotificationTypeID { get; set; }
        public string Message { get; set; }
        public System.DateTime Dated { get; set; }
        public long? FromUserID { get; set; }
        public bool IsGeneratedFromSystem { get; set; }
        public bool IsSeen { get; set; }
        public byte RelatedIDTypeID { get; set; }
    
        public virtual NotificationType NotificationType { get; set; }
        public virtual RelatedIDType RelatedIDType { get; set; }
    }
}
