//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewLikeDislike
    {
        public long ReviewLikeDislikeID { get; set; }
        public long ReviewID { get; set; }
        public long UserID { get; set; }
        public bool IsLiked { get; set; }
        public bool IsDisliked { get; set; }
        public bool IsNone { get; set; }
    
        public virtual Review Review { get; set; }
        public virtual User User { get; set; }
    }
}
