//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchIndex
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SearchIndex()
        {
            this.SearchedAppsFounds = new HashSet<SearchedAppsFound>();
            this.SearchedBlogArticleFounds = new HashSet<SearchedBlogArticleFound>();
        }
    
        public long SearchIndexID { get; set; }
        public string SearchText { get; set; }
        public System.DateTime SearchedAt { get; set; }
        public int AvailableAppsCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchedAppsFound> SearchedAppsFounds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SearchedBlogArticleFound> SearchedBlogArticleFounds { get; set; }
    }
}
