//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public long SubscribeID { get; set; }
        public Nullable<long> SubscribedByUserID { get; set; }
        public long SubscribedToUserID { get; set; }
        public string SubscribedByEmail { get; set; }
        public bool IsSubscribedByUser { get; set; }
        public bool IsSubscribedByNonUser { get; set; }
        public long MailsSend { get; set; }
        public Nullable<System.DateTime> LastSendAt { get; set; }
    }
}
