//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagAppRelations = new HashSet<TagAppRelation>();
        }
    
        public long TagID { get; set; }
        public string TagDisplay { get; set; }
    
        public virtual ICollection<TagAppRelation> TagAppRelations { get; set; }
    }
}
