//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewApps.Models.EntityModel {
    using System;
    using System.Collections.Generic;

    public partial class UserPointSetting {
        public UserPointSetting() {
            this.UserPoints = new HashSet<UserPoint>();
        }

        public byte UserPointSettingID { get; set; }
        public string TaskName { get; set; }
        public int Point { get; set; }

        public virtual ICollection<UserPoint> UserPoints { get; set; }
    }
}
