//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereViewApp.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppDraft
    {
        public long AppDraftID { get; set; }
        public string AppName { get; set; }
        public byte PlatformID { get; set; }
        public short CategoryID { get; set; }
        public string Description { get; set; }
        public long PostedByUserID { get; set; }
        public Nullable<short> ReviewsCount { get; set; }
        public Nullable<bool> IsVideoExist { get; set; }
        public string YoutubeEmbedLink { get; set; }
        public string WebsiteUrl { get; set; }
        public string StoreUrl { get; set; }
        public Nullable<bool> IsBlocked { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<double> PlatformVersion { get; set; }
        public System.Guid UploadGuid { get; set; }
        public Nullable<long> TotalViewed { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
    }
}
