//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereViewApp.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CellPhone
    {
        public long CellPhoneID { get; set; }
        public long UserID { get; set; }
        public byte PlatformID { get; set; }
        public double PlatformVersion { get; set; }
    
        public virtual Platform Platform { get; set; }
        public virtual User User { get; set; }
    }
}
