//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereViewApp.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public long MessageID { get; set; }
        public string Msg1 { get; set; }
        public string Msg2 { get; set; }
        public string Msg3 { get; set; }
        public string Msg4 { get; set; }
        public string MessageDisplay { get; set; }
        public long SenderUserID { get; set; }
        public long ReceiverUserID { get; set; }
        public bool IsDraft { get; set; }
        public System.DateTime LastModified { get; set; }
        public System.DateTime SentDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsReceived { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
