//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WereViewApp.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPoint
    {
        public long UserPointID { get; set; }
        public long UserID { get; set; }
        public int Point { get; set; }
        public byte UserPointSettingID { get; set; }
        public System.DateTime Dated { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserPointSetting UserPointSetting { get; set; }
    }
}
